### ISSUE TITLE
Images not matching items

### ISSUE THREAD

**Issue by Running-Water** [gtjamesa/ge-tracker-app#115]
The shown image for certain items is not the correct one.

Have a gander at the Cowhide item on your app 

**Expected behaviour**
Been shown the image of a cowhide

**Screenshots**
Check the Discord server 

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 12.1.1
 - Version: 0.8.0

**Comment by gtjamesa** [comment]
Will be patched in 0.8.1
