### ISSUE TITLE
transaction not verified

### ISSUE THREAD

**Issue by Loukhi** [gtjamesa/ge-tracker-app#118]
**Describe the bug**
I created an account on GE Tracker two days ago through the app. My temporary premium membership ran out about an hour ago so I purchased the 3 month for $9.99 subscription on the app. I made the purchase through google play. After completing the transaction a brief note popped up that said something along the lines of "Subscription not verified". I attempted to access premium content and I was still restricted from access, I checked to see if the purchase just didn't go through and tried to make the purchase again and it said "you've already purchased this item" or something along these lines. I checked my bank account and it showed that the transaction is in fact processing in the bank. I confirmed that my email was verified and attempted to sign out and back in.
**To Reproduce**
see above. 

**Expected behaviour**
Premium access
**Screenshots**
**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+

**Comment by gtjamesa** [comment]
Hi,

Sorry to hear you are having trouble subscribing via the app. We have recently turned our firewall to high sensitivity and this may have affected some subscription

Could you please provide your **Google Play Order ID* - you will be able to find this in the receipt you were emailed when your purchase was authorised. It will look like the following:

```
 Order number: GPA.3344-5130-1234-12345..1
```

Is your GT username 'Loukhi'? If so, I have granted you an additional trial so you can use the premium features immediately. If you could either reply here or email it to support@ge-tracker.com, I will get your account updated ASAP.

Kind regards,

James

**Comment by Loukhi** [comment]
yes Loukhi is me, thank you for all of your help. a person named
BenefitsOfaCow with support is also trying to help me, as I reached out
through both means of contact.
