### ISSUE TITLE
90% of the content is all of a sudden locked behind cash grabs. It worked as a free app for days, but then all of a sudden everything is blocked unless youre a premium member. Dont know if it is intentional or a glitch. 

### ISSUE THREAD

**Issue by CheerUpDvo** [gtjamesa/ge-tracker-app#120]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gtjamesa** [comment]
We have a 2-day free trial on both our mobile app and website. You can see a pricing breakdown and comparison of the features here: https://www.ge-tracker.com/pricing
