### ISSUE TITLE
Wrong item image

### ISSUE THREAD

**Issue by Inscipio** [gtjamesa/ge-tracker-app#121]
**Describe the bug**
Every single item I look up in the shop has a dhcb picture. 

**To Reproduce**
1. Search any item in the game
2. Click on the item in the drop down
3. It had dhcb image

**Expected behaviour**
the item has the correct image

**Screenshots**
![502B0B04-114D-4930-B596-0138702A4B16](https://user-images.githubusercontent.com/43582536/102720401-f3f83100-42a8-11eb-986e-387038abf73c.png)
![8F4D80BF-8A60-46A2-9B5D-054629FB3F01](https://user-images.githubusercontent.com/43582536/102720402-f5c1f480-42a8-11eb-8061-7def37b0f198.png)
![254C09BA-C74F-4AB0-A007-B36126C16CB6](https://user-images.githubusercontent.com/43582536/102720404-f65a8b00-42a8-11eb-878e-ca55f8d91765.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.2
 - Version 14.2

**Additional context**

**Comment by GETrackerDan** [comment]
You're not using the latest version. Check for app updates on App store.
