### ISSUE TITLE
Item Sets do not work on the app, and section missing on website

### ISSUE THREAD

**Issue by xmegalolzx** [gtjamesa/ge-tracker-app#122]
On the app,  Item Sets under the Money Making section does not load.    The section is also now missing from the website. This was the only reason I got premium.

**Comment by GETrackerDan** [comment]
Item sets is located under **item conversions**
https://www.ge-tracker.com/item-sets on the website


But can confirm item-sets under the app isn't loading.

@gtjamesa can you take a look?

**Comment by gtjamesa** [comment]
I'll take a look into why the Item Sets page isn't loading, and I'll go ahead and add the new "Combination Items" page while I'm at it too :)

**Comment by gtjamesa** [comment]
Item Sets page is fixed on the mobile app @xmegalolzx. No update required.
