### ISSUE TITLE
Payed for 1 month membership twice never received it

### ISSUE THREAD

**Issue by YipIz** [gtjamesa/ge-tracker-app#125]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here. Payed twice didn’t receive?

**Comment by gtjamesa** [comment]
Press this link and it'll redirect you to your Purchased history on the App-Store: https://finance-app.itunes.apple.com/purchases

On there it'll show your Ge-Tracker Purchase, Select the GT Purchase and screenshot that page. It'll include the Order ID Number and Document Number which we need to apply your Premium membership.

If you can send that screenshot to support@ge-tracker.com, we'll get it sorted for you :)
