### ISSUE TITLE
What’s the deal?!

### ISSUE THREAD

**Issue by FknAnt** [gtjamesa/ge-tracker-app#126]
I paid for membership and was charged and haven’t received it

**Describe the bug**
A clear and concise description of wha the bug is.

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gtjamesa** [comment]
Press this link and it'll redirect you to your Purchased history on the App-Store: https://finance-app.itunes.apple.com/purchases

On there it'll show your Ge-Tracker Purchase, Select the GT Purchase and screenshot that page. It'll include the **Order ID Number** and **Document Number** which we need to apply your Premium membership.

If you can send that screenshot to support@ge-tracker.com, we'll get it sorted for you :)

If you are on Android, please email for further details.
