### ISSUE TITLE
Membership not activated 

### ISSUE THREAD

**Issue by Rotorgoboom** [gtjamesa/ge-tracker-app#127]
I recently bought membership and my account had not upgraded even after 2 days.

**Comment by gtjamesa** [comment]
Press this link and it'll redirect you to your Purchased history on the App-Store: https://finance-app.itunes.apple.com/purchases

On there it'll show your Ge-Tracker Purchase, Select the GT Purchase and screenshot that page. It'll include the Order ID Number and Document Number which we need to apply your Premium membership.

If you can send that screenshot to support@ge-tracker.com, we'll get it sorted for you :)
