### ISSUE TITLE
Premium payment not going through

### ISSUE THREAD

**Issue by Beachbionic** [gtjamesa/ge-tracker-app#130]
Paid for premium membership 2 times and both times it didn’t go through. I only have access to free when my phone told me payment successful. Payment came out too of my bank. IOS device.

**Comment by gtjamesa** [comment]
Press this link and it'll redirect you to your Purchased history on the App-Store: (https://finance-app.itunes.apple.com/purchases)

On there it'll show your Ge-Tracker Purchase, Select the GT Purchase and screenshot that page. It'll include the **Order ID** Number and **Document Number** which we need to apply your Premium membership.

If you can send that screenshot to [support@ge-tracker.com](mailto:support@ge-tracker.com), we'll get it sorted for you :)

**Comment by Beachbionic** [comment]
I did this and have got nothing back. How long does it usually take to go
through?
