### ISSUE TITLE
Logging out in landscape mode does not let you go back to portrait

### ISSUE THREAD

**Issue by gtjamesa** [gtjamesa/ge-tracker-app#22]
@PrimoVG

**Comment by Vacrin** [comment]
I believe I found the issue, this should be resolved now. Needs testing.

**Comment by PrimoVG** [comment]
@Vacrin Opened a new issue (just saw this thread(new to github lol)). Added a screenshot as well there. 
the ghraps will be opened in landscape, but the main page/item pages look different.

**Comment by gtjamesa** [comment]
Confirmed fixed, nice work @Vacrin
