### ISSUE TITLE
No link to wikipedia pages

### ISSUE THREAD

**Issue by PrimoVG** [gtjamesa/ge-tracker-app#23]
https://i.imgur.com/pgWb8LN.png

**Comment by gtjamesa** [comment]
Open to options about where/how the wiki link displayed

**Comment by PrimoVG** [comment]
I'd use another tab. Something like: usefull links.

**Comment by gtjamesa** [comment]
I like the idea of tabs, plus it gives us the option to add a couple more in the future as more features are added

**Comment by PrimoVG** [comment]
yeah i agree. Could name it something like other resources. Then you can always add extra options (appart from links)

**Comment by gtjamesa** [comment]
Implemented, will be released in 0.0.19
