### ISSUE TITLE
Option to filter out negative prices

### ISSUE THREAD

**Issue by PrimoVG** [gtjamesa/ge-tracker-app#30]
On mobile, the prices where you can make a loss on take up allot of space. It would be nice to be able to filter them so there is less clutter (on own risk ofc)
https://i.imgur.com/acHW53K.png

**Comment by gtjamesa** [comment]
Once the iOS build is ready I'll take a look at adding the filters button, and we can add a sort along with this.

We could include some additional filters (mobile-only) that can filter out any negative values?

**Comment by PrimoVG** [comment]
Yeah i think adding mobile only filters would be a good idea. Since (imo) there is no need to filter them out on pc.
