### ISSUE TITLE
Duplicate keys when rendering search results with "View Flipping Info" enabled

### ISSUE THREAD

**Issue by gtjamesa** [gtjamesa/ge-tracker-app#35]
It seems like this was introduced with #32.

The render time when enabling the switch is pretty slow, could we change the Array.map() call to a [FlatList](https://facebook.github.io/react-native/docs/flatlist.html) component so only the items that are on-screen or can be immediately scrolled to are rendered?

![Duplicate keys](https://i.imgur.com/3hriZZP.png "Duplicate keys")

**Comment by Vacrin** [comment]
Switched to FlatList too, removed dup key problem.
