### ISSUE TITLE
Stuck on horizontal

### ISSUE THREAD

**Issue by PrimoVG** [gtjamesa/ge-tracker-app#37]
When closing the graph, the screen orients from horizontal (leaving the graph) to vertical (back to item details) and then back to horizontal again, regardless of the original or current orientation of the phone

**Comment by PrimoVG** [comment]
https://mega.nz/#!C9IVWKia!taGzZvVvhCcy0gdSxMCfpHiCr5PYBPtGPz_WiZNaoFQ

**Comment by gtjamesa** [comment]
Is this still an issue?

**Comment by gtjamesa** [comment]
Will be patched in 0.6.1
