### ISSUE TITLE
Deleting favourite item issue

### ISSUE THREAD

**Issue by GETrackerDan** [gtjamesa/ge-tracker-app#47]
When deleting a item from your favourite list causes icons to move down to next item.

Picture shows that I deleted magic sapling from my favourite items. 

Happening on Android ; Haven't tested on iOS![Image](https://i.imgur.com/C0tn768_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by gtjamesa** [comment]
Good spot! Has the pricing dropped down too or is it just the icons?

**Comment by GETrackerDan** [comment]
Prices seem fine. Only appears to be the item image.

**Comment by GETrackerDan** [comment]
Tested on latest iOS and can confirm same issue is on both platforms.

**Comment by gtjamesa** [comment]
Fixed, will be released in 0.3.0
