### ISSUE TITLE
Graph landscape issue. 

### ISSUE THREAD

**Issue by GETrackerDan** [gtjamesa/ge-tracker-app#60]
Dates on graph in landscape mode is squashed together and unreadable.

 https://i.imgur.com/x1oA8cH.jpg

**Comment by GETrackerDan** [comment]
Seems to have been a one-off seems to be working fine after a few attempts.

**Comment by gtjamesa** [comment]
Let me know if this keeps happening. 

I've pulled the current graph source apart and extracted it into several components (currently in use on the Profit Tracker graph) and in the process I've optimised the rendering of the graphs - in their current state (Item Graphs) they're doing ~5 renders before actually showing the graph, I've reduced this to 1, so this might be an initial rendering issue
